version: "3.8"
services:
  database:
    container_name: db_api_cooking_recipes
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_api_cooking_recipes
      MYSQL_USER: api_cooking_recipes
      MYSQL_PASSWORD: apicookingrecipes
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php_api_cooking_recipes
    build:
      context: ./php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        GIT_EMAIL: ${GIT_EMAIL}
        GIT_NAME: ${GIT_NAME}
    links:
      - "database:database"
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/app
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8085:80'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
volumes:
  app: